[tool.poetry]
name = "my_project"
version = "0.1.0"
description = ""
authors = ["Borja borjaf696@gmail.com"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
pandas = ">=1.1.5"
scipy = ">=1.11.1"
seaborn = ">=0.12.2"
scikit-learn = ">=1.3.0"
tensorflow = ">=2.11.0"
pydot = ">=1.4.2"
wandb = ">=0.15.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
